name: flake8
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: install everything with poetry
        run: poetry install -v
      - name: Run flake8
        run: poetry run flake8 --count --statistics --max-line-length=120 nchainz
